spring.application.name=Finsecure

#Server
server.port=8080

#Virtual Threads
spring.threads.virtual.enabled=true

#Database
spring.datasource.url=jdbc:postgresql://localhost:5432/finsecure
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

#JWT

jwt.secret=cWZShxssMgmWU9jVX8Cr0RMP2MbVzWtNgRtbCEecap8=
jwt.expiration-ms=86400000

#SpringDoc / Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

#Logging
logging.pattern.console=%clr(%d{HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%X{requestId}]){magenta} %clr(%-40.40logger{39}){cyan} : %m%n
logging.level.com.finSecure=DEBUG
logging.level.org.springframework.security=WARN
logging.level.org.hibernate.SQL=WARN